### ISSUE TITLE
Can't use WorksWith example due to Data Capture Lab community edition limits

### ISSUE THREAD

**Issue by pres2300** [sensiml/sensiml_xG24_recognition_dual_IMU_audio#4]
The Data Capture Lab won't run the "Smart_Lock_IMU" project due to a cloud sync error.  It exceeds the free version limits.

Is there a way to turn off cloud sync to be able to continue with this learning opportunity?

**Comment by cdknorow** [comment]
Hi Jacob,

Please use the project that is stored here. It has a lower number of segments and will work with this tutorial 

https://sensiml-data-depot.s3.us-west-2.amazonaws.com/workswith-2022/Smart_Lock_IMU.zip
https://sensiml-data-depot.s3.us-west-2.amazonaws.com/workswith-2022/Smart_Lock_Audio.zip

Best,
CK

**Comment by pres2300** [comment]
Thanks, those projects resolve the issue with the community edition limits.
